version: '3'
services:
    worlds-postgres:
        image: postgres
        ports:
            - "127.0.0.1:5432:5432"
        environment:
            POSTGRES_DB: worlds
            POSTGRES_USER: worlds
            POSTGRES_PASSWORD: worlds
    worlds-service:
        image: worlds/service:0.0.1-SNAPSHOT
        links:
            - worlds-postgres:postgres
        ports:
            - "127.0.0.1:8080:8080"
        environment:
            PG_URI: jdbc:postgresql://postgres:5432/worlds?user=worlds&password=worlds
    worlds-webapp:
        image: worlds/webapp:0.0.1-SNAPSHOT
        ports: 
            - "127.0.0.1:8000:80"
        environment:
            REACT_APP_AUTH_URL: http://localhost:8080/openid/authorize
            REACT_APP_AUTH_CLIENT: 4BBBDEB7-4A30-454A-B1BC-A7529204DBCC
            REACT_APP_AUTH_CALLBACK: http://localhost:8000/auth/callback.html
            REACT_APP_API_BASE: http://localhost:8080/api
