version: '3'
services:
    worlds-postgres:
        image: postgres
        environment:
            POSTGRES_DB: worlds
            POSTGRES_USER: worlds
            POSTGRES_PASSWORD: worlds
    worlds-backend:
        build: backend
        ports:
            - "127.0.0.1:4000:4000"
        environment:
            PORT: 4000
            NODE_ENV: production
            POSTGRES_HOST: worlds-postgres
            POSTGRES_PORT: 5432
            POSTGRES_DB: worlds
            POSTGRES_USER: worlds
            POSTGRES_PASSWORD: worlds
    worlds-webapp:
        build: webapp
        ports:
            - "127.0.0.1:3000:80"
        environment:
            API_URI: http://localhost:4000
