version: '3'
services:
    worlds-cucumber-postgres:
        image: postgres
        environment:
            POSTGRES_DB: worlds-cucumber
            POSTGRES_USER: worlds-cucumber
            POSTGRES_PASSWORD: worlds-cucumber
    worlds-cucumber-backend:
        build: .
        environment:
            PORT: 3000
            NODE_ENV: production
            POSTGRES_HOST: worlds-cucumber-postgres
            POSTGRES_PORT: 5432
            POSTGRES_DB: worlds-cucumber
            POSTGRES_USER: worlds-cucumber
            POSTGRES_PASSWORD: worlds-cucumber
    worlds-cucumber-cucumber:
        build: .
        command: dockerize -wait tcp://worlds-cucumber-backend:3000 yarn cucumber
        environment:
            NODE_ENV: production
            POSTGRES_HOST: worlds-cucumber-postgres
            POSTGRES_PORT: 5432
            POSTGRES_DB: worlds-cucumber
            POSTGRES_USER: worlds-cucumber
            POSTGRES_PASSWORD: worlds-cucumber
            API_URL: http://worlds-cucumber-backend:3000
