CREATE TABLE users(
    user_id UUID PRIMARY KEY,
    version UUID NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(260) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
);
