CREATE TABLE users(
    user_id UUID NOT NULL PRIMARY KEY,
    version UUID NOT NULL,
    created TIMESTAMP WITH TIME ZONE NOT NULL,
    updated TIMESTAMP WITH TIME ZONE NOT NULL,
    email VARCHAR(260) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    password_hash VARCHAR(256) NOT NULL,
    password_salt VARCHAR(256) NOT NULL
);
